In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
dataset = pd.read_csv(r'/Users/sehan/Documents/Dataset/Multi_New/top_25_multi.csv')

In [13]:
dataset.head()

Load  SrcTCPBase  tcp  udp  RST  INT  sHops  dTtl   e s        Loss  ...  \
0   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
1   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
2   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
3   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
4   0.0         NaN    0    0    0    0    6.0  64.0           0     0  ...   

   dMeanPktSz  ACC  dHops  SrcPkts  DstWin  TotBytes   e d        REQ  \
0       154.0    0    1.0        1     NaN       243           0    0   
1       154.0    0    1.0        1     NaN       243           0    0   
2       264.0    0    1.0        1     NaN       340           0    0   
3       141.0    0    1.0        1     NaN       217           0    0   
4        98.0    0    0.0        1     NaN       200           0    0   

   DstLoss  Attack Type  
0        0            0  
1        0            0  
2        0            0  
3        0            0  
4        0            0  

[5 rows x 26 columns]

In [14]:
dataset = dataset.fillna(dataset.median())
print(dataset)

                Load    SrcTCPBase  tcp  udp  RST  INT  sHops   dTtl  \
0       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
1       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
2       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
3       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
4       0.000000e+00  1.490814e+09    0    0    0    0    6.0   64.0   
...              ...           ...  ...  ...  ...  ...    ...    ...   
851199  8.619034e+06  1.490814e+09    0    1    0    0   11.0   64.0   
851200  3.068197e+06  1.490814e+09    0    1    0    0   11.0   64.0   
851201  3.064397e+04  1.490814e+09    0    1    0    0    0.0  117.0   
851202  3.179072e+04  1.490814e+09    0    1    0    0    0.0  117.0   
851203  5.227891e+05  1.490814e+09    0    1    0    0   11.0   64.0   

         e s        Loss  ...  dMeanPktSz  ACC  dHops  SrcPkts  DstWin  \
0                0     0  ...  154.000000    0    1.0        

In [37]:
dataset = dataset.drop(columns=['SrcBytes', 'ACC', 'dHops','FIN'])

In [15]:
X = dataset.iloc[:,0:24].values
y = dataset.iloc[:,25].values

In [16]:
#test and train split (30% for test)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [17]:
#data normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [18]:
import time
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, leaf_size=100)
start = time.time()
classifier.fit(X_train, y_train)
stop = time.time()
print(f"Training time: {stop - start}s")

Training time: 0.09027719497680664s


In [19]:
start = time.time()
y_pred = classifier.predict(X_test)
stop = time.time()
print(f"Prediction time: {stop - start}s")

Prediction time: 5769.97722697258s


In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))
print(accuracy_score(y_test, y_pred))

[[ 9931     5     2     0    18    19     3]
 [    3  9679     0     0     6     2     9]
 [    0     0 67352     0     0     0     0]
 [    0     0     0 79851     0     0     0]
 [    0     0     0     0 46768     0     0]
 [    2     6     0     0    13 28514   147]
 [    0     0     0     0     0   382 12650]]
              precision    recall  f1-score   support

           0     0.9995    0.9953    0.9974      9978
           1     0.9989    0.9979    0.9984      9699
           2     1.0000    1.0000    1.0000     67352
           3     1.0000    1.0000    1.0000     79851
           4     0.9992    1.0000    0.9996     46768
           5     0.9861    0.9941    0.9901     28682
           6     0.9876    0.9707    0.9791     13032

    accuracy                         0.9976    255362
   macro avg     0.9959    0.9940    0.9949    255362
weighted avg     0.9976    0.9976    0.9976    255362

0.9975838221818438


In [10]:
classifier.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}