In [63]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [54]:
dataset = pd.read_csv(r'/Users/sehan/Documents/Dataset/Multi_New/top_25_multi.csv')

In [55]:
dataset.head()

Load  SrcTCPBase  tcp  udp  RST  INT  sHops  dTtl   e s        Loss  ...  \
0   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
1   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
2   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
3   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
4   0.0         NaN    0    0    0    0    6.0  64.0           0     0  ...   

   dMeanPktSz  ACC  dHops  SrcPkts  DstWin  TotBytes   e d        REQ  \
0       154.0    0    1.0        1     NaN       243           0    0   
1       154.0    0    1.0        1     NaN       243           0    0   
2       264.0    0    1.0        1     NaN       340           0    0   
3       141.0    0    1.0        1     NaN       217           0    0   
4        98.0    0    0.0        1     NaN       200           0    0   

   DstLoss  Attack Type  
0        0            0  
1        0            0  
2        0            0  
3        0            0  
4        0            0  

[5 rows x 26 columns]

In [56]:
dataset = dataset.fillna(dataset.median())
display(dataset)

Load    SrcTCPBase  tcp  udp  RST  INT  sHops   dTtl  \
0       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
1       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
2       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
3       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
4       0.000000e+00  1.490814e+09    0    0    0    0    6.0   64.0   
...              ...           ...  ...  ...  ...  ...    ...    ...   
851199  8.619034e+06  1.490814e+09    0    1    0    0   11.0   64.0   
851200  3.068197e+06  1.490814e+09    0    1    0    0   11.0   64.0   
851201  3.064397e+04  1.490814e+09    0    1    0    0    0.0  117.0   
851202  3.179072e+04  1.490814e+09    0    1    0    0    0.0  117.0   
851203  5.227891e+05  1.490814e+09    0    1    0    0   11.0   64.0   

         e s        Loss  ...  dMeanPktSz  ACC  dHops  SrcPkts  DstWin  \
0                0     0  ...  154.000000    0    1.0        1   508.0   
1                0     0  ...  154.000000    0    1.0        1   508.0   
2                0     0  ...  264.000000    0    1.0        1   508.0   
3                0     0  ...  141.000000    0    1.0        1   508.0   
4                0     0  ...   98.000000    0    0.0        1   508.0   
...            ...   ...  ...         ...  ...    ...      ...     ...   
851199           0     0  ...  384.090912    0    0.0       73   508.0   
851200           0     0  ...  171.000000    0    0.0       96   508.0   
851201           0     0  ...   73.000000    0   11.0        2   508.0   
851202           0     0  ...   73.000000    0   11.0        2   508.0   
851203           0     0  ...  207.409088    0    0.0        3   508.0   

        TotBytes   e d        REQ  DstLoss  Attack Type  
0            243           0    0        0            0  
1            243           0    0        0            0  
2            340           0    0        0            0  
3            217           0    0        0            0  
4            200           0    0        0            0  
...          ...         ...  ...      ...          ...  
851199     94263           0    0        0            0  
851200    134293           0    0        0            0  
851201       445           0    0        0            0  
851202       445           0    0        0            0  
851203      4767           0    0        0            0  

[851204 rows x 26 columns]

In [57]:
X = dataset.iloc[:,0:24].values
y = dataset.iloc[:,25].values

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [60]:
import time
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes=(10,20,10), max_iter=1000)
start = time.time()
MLP.fit(X_train, y_train)
stop = time.time()
print(f"Training time: {stop - start}s")

Training time: 461.1033890247345s


In [51]:
start = time.time()
y_pred = MLP.predict(X_test)
stop = time.time()
print(f"Prediction time: {stop - start}s")

Prediction time: 0.8262348175048828s


In [52]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))
print(accuracy_score(y_test, y_pred))

[[ 9948     5     1     0    11     9     4]
 [   51  9637     0     0     4     0     7]
 [    0     0 67352     0     0     0     0]
 [    0     0     0 79851     0     0     0]
 [    0     0     0     0 46768     0     0]
 [    2     0     0     0     1 28639    40]
 [    0     1     0     0     0   143 12888]]
              precision    recall  f1-score   support

           0     0.9947    0.9970    0.9958      9978
           1     0.9994    0.9936    0.9965      9699
           2     1.0000    1.0000    1.0000     67352
           3     1.0000    1.0000    1.0000     79851
           4     0.9997    1.0000    0.9998     46768
           5     0.9947    0.9985    0.9966     28682
           6     0.9961    0.9890    0.9925     13032

    accuracy                         0.9989    255362
   macro avg     0.9978    0.9969    0.9973    255362
weighted avg     0.9989    0.9989    0.9989    255362

0.9989074333690996
