In [92]:
import pandas as pd
import numpy as np

In [93]:
dataset = pd.read_csv(r'/Users/sehan/Documents/Dataset/Multi_New/top_25_multi.csv')

In [94]:
dataset.head()

Load  SrcTCPBase  tcp  udp  RST  INT  sHops  dTtl   e s        Loss  ...  \
0   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
1   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
2   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
3   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
4   0.0         NaN    0    0    0    0    6.0  64.0           0     0  ...   

   dMeanPktSz  ACC  dHops  SrcPkts  DstWin  TotBytes   e d        REQ  \
0       154.0    0    1.0        1     NaN       243           0    0   
1       154.0    0    1.0        1     NaN       243           0    0   
2       264.0    0    1.0        1     NaN       340           0    0   
3       141.0    0    1.0        1     NaN       217           0    0   
4        98.0    0    0.0        1     NaN       200           0    0   

   DstLoss  Attack Type  
0        0            0  
1        0            0  
2        0            0  
3        0            0  
4        0            0  

[5 rows x 26 columns]

In [95]:
dataset = dataset.fillna(dataset.median())
print(dataset)

                Load    SrcTCPBase  tcp  udp  RST  INT  sHops   dTtl  \
0       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
1       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
2       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
3       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
4       0.000000e+00  1.490814e+09    0    0    0    0    6.0   64.0   
...              ...           ...  ...  ...  ...  ...    ...    ...   
851199  8.619034e+06  1.490814e+09    0    1    0    0   11.0   64.0   
851200  3.068197e+06  1.490814e+09    0    1    0    0   11.0   64.0   
851201  3.064397e+04  1.490814e+09    0    1    0    0    0.0  117.0   
851202  3.179072e+04  1.490814e+09    0    1    0    0    0.0  117.0   
851203  5.227891e+05  1.490814e+09    0    1    0    0   11.0   64.0   

         e s        Loss  ...  dMeanPktSz  ACC  dHops  SrcPkts  DstWin  \
0                0     0  ...  154.000000    0    1.0        

In [96]:
X = dataset.iloc[:,0:24].values
y = dataset.iloc[:,25].values

In [97]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

In [98]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [99]:
import time
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10,random_state=0)
start = time.time()
classifier.fit(X_train, y_train)
stop = time.time()
print(f"Training time: {stop - start}s")


Training time: 7.686552047729492s


In [100]:
start = time.time()
y_pred = classifier.predict(X_test)
stop = time.time()
print(f"Prediction time: {stop - start}s")

Prediction time: 0.3904449939727783s


In [101]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))
print(accuracy_score(y_test, y_pred))

[[ 9593   378     4     0     1     2     0]
 [   15  9674     0     0     0    10     0]
 [    0     0 67352     0     0     0     0]
 [    0   528     0 79323     0     0     0]
 [ 1699     0     0     0 45069     0     0]
 [   59     1     0     0     0 28557    65]
 [   21   458     0     0    15  2768  9770]]
              precision    recall  f1-score   support

           0     0.8425    0.9614    0.8980      9978
           1     0.8763    0.9974    0.9330      9699
           2     0.9999    1.0000    1.0000     67352
           3     1.0000    0.9934    0.9967     79851
           4     0.9996    0.9637    0.9813     46768
           5     0.9113    0.9956    0.9516     28682
           6     0.9934    0.7497    0.8545     13032

    accuracy                         0.9764    255362
   macro avg     0.9462    0.9516    0.9450    255362
weighted avg     0.9788    0.9764    0.9761    255362

0.9764099591951817
