In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r'/Users/sehan/Documents/Dataset/Multi_New/top_25_multi.csv')

In [3]:
dataset.head()

Load  SrcTCPBase  tcp  udp  RST  INT  sHops  dTtl   e s        Loss  ...  \
0   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
1   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
2   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
3   0.0         NaN    0    1    0    0    0.0  63.0           0     0  ...   
4   0.0         NaN    0    0    0    0    6.0  64.0           0     0  ...   

   dMeanPktSz  ACC  dHops  SrcPkts  DstWin  TotBytes   e d        REQ  \
0       154.0    0    1.0        1     NaN       243           0    0   
1       154.0    0    1.0        1     NaN       243           0    0   
2       264.0    0    1.0        1     NaN       340           0    0   
3       141.0    0    1.0        1     NaN       217           0    0   
4        98.0    0    0.0        1     NaN       200           0    0   

   DstLoss  Attack Type  
0        0            0  
1        0            0  
2        0            0  
3        0            0  
4        0            0  

[5 rows x 26 columns]

In [4]:
dataset = dataset.fillna(dataset.median())
print(dataset)

                Load    SrcTCPBase  tcp  udp  RST  INT  sHops   dTtl  \
0       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
1       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
2       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
3       0.000000e+00  1.490814e+09    0    1    0    0    0.0   63.0   
4       0.000000e+00  1.490814e+09    0    0    0    0    6.0   64.0   
...              ...           ...  ...  ...  ...  ...    ...    ...   
851199  8.619034e+06  1.490814e+09    0    1    0    0   11.0   64.0   
851200  3.068197e+06  1.490814e+09    0    1    0    0   11.0   64.0   
851201  3.064397e+04  1.490814e+09    0    1    0    0    0.0  117.0   
851202  3.179072e+04  1.490814e+09    0    1    0    0    0.0  117.0   
851203  5.227891e+05  1.490814e+09    0    1    0    0   11.0   64.0   

         e s        Loss  ...  dMeanPktSz  ACC  dHops  SrcPkts  DstWin  \
0                0     0  ...  154.000000    0    1.0        

In [5]:
X = dataset.iloc[:,0:24].values
y = dataset.iloc[:,25].values

In [6]:
#test and train split (30% for test)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.80)

In [7]:
#data normalization
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler(feature_range=(-1,1)).fit(X_train)
X_train = scaling.transform(X_train)
X_test = scaling.transform(X_test)

In [8]:
from sklearn.svm import SVC
model = SVC()

In [9]:
import time
start = time.time()
model.fit(X_train, y_train)
stop = time.time()
print(f"Training time: {stop - start}s")

Training time: 110.53243899345398s


In [10]:
start = time.time()
y_pred = model.predict(X_test)
stop = time.time()
print(f"Prediction time: {stop - start}s")

Prediction time: 1569.6127078533173s


In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))
print(accuracy_score(y_test, y_pred))

[[ 22585    224    184   1009    630   1221    538]
 [    71  20976      0      2   4740      5     16]
 [     0      0 178714      0      0      0      0]
 [     0      0      0 213627      0      0      0]
 [     0      0      0      0 124859      0      0]
 [    14     11      0     11    441  72547   3860]
 [     0      0      0      3      0   6047  28629]]
              precision    recall  f1-score   support

           0     0.9963    0.8558    0.9207     26391
           1     0.9889    0.8127    0.8922     25810
           2     0.9990    1.0000    0.9995    178714
           3     0.9952    1.0000    0.9976    213627
           4     0.9555    1.0000    0.9773    124859
           5     0.9089    0.9436    0.9259     76884
           6     0.8664    0.8255    0.8455     34679

    accuracy                         0.9721    680964
   macro avg     0.9586    0.9197    0.9369    680964
weighted avg     0.9724    0.9721    0.9716    680964

0.9720587285084087
